import type { Metadata } from "next";
import { Nunito_Sans as NS } from "next/font/google";
import "./globals.css";
import Sidenav from "@/modules/sidenav";
import Topnav from "@/modules/topnav";
import { MenuToggleProvider } from "@/modules/Contexts/MenuToggleContext";

const ns = NS({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={ns.className}>
				<MenuToggleProvider>
					<div className=" flex bg-CBG">
						<div className="w-fit">
							<Sidenav />
						</div>
						<div className=" flex-auto">
							<Topnav />
							<main className="m-5">{children}</main>
						</div>
					</div>
				</MenuToggleProvider>
			</body>
		</html>
	);
}
