import type { Metadata } from "next";
import { Nunito_Sans as NS } from "next/font/google";
import "./globals.css";
import Sidenav from "@/app/ui/sidenav";
import Topnav from "@/app/ui/topnav";

const ns = NS({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={ns.className}>
				<div className=" flex bg-CBG">
					<div className="w-[240px]">
						<Sidenav />
					</div>
					<div className="w-full">
						<Topnav />
						<main className="p-5">{children}</main>
					</div>
				</div>
			</body>
		</html>
	);
}
